### ISSUE TITLE
High gains broken while using high framerates, image looks yellowed

### ISSUE THREAD

**Issue by skronstein** [krontech/chronos-cam-app#33]
Image looks more yellow than it should at these framerates and gains:
framerate above 31.99kfps at gain 12
framerate above 11.11kfps at gain 24

**Comment by oskirby** [comment]
The yellow is due to the fact that the image is digitally gained up via the the color matrix to compensate for the loss of dynamic range due to FPN subtraction. The FPN is generally small at low gains or long wavetables but when the gain is high and the wavetable is short then the digital gain pushes the color matrix out of the range that the FPGA can accept, resulting in distorted color.
